In [448]:
import pandas as pd
import numpy as np
import sklearn

In [449]:
%pip install scikit-learn

### **1. Loading the dataset into a DataFrame.**

In [450]:
df = pd.read_csv('alarms-240222-010325.csv', header=0, sep=';')

In [451]:
df

id  region_id         region_city  all_region                start  \
0       52432         12      Львівська обл.           1  2022-02-24 07:43:17   
1       53292         23   Чернігівська обл.           1  2022-02-24 14:00:43   
2       52080          3      Вінницька обл.           1  2022-02-24 15:40:42   
3       52857         19     Харківська обл.           1  2022-02-24 20:11:47   
4       52700         18  Тернопільська обл.           1  2022-02-25 01:59:36   
...       ...        ...                 ...         ...                  ...   
55783  158642         14        Одеська обл.           1  2025-03-01 21:49:30   
55784  158635          9       Київська обл.           1  2025-03-01 22:20:51   
55785  158636          9                Київ           0  2025-03-01 22:52:10   
55786  158617          3      Вінницька обл.           1  2025-03-01 23:26:07   
55787  158629          6    Житомирська обл.           1  2025-03-01 23:26:07   

                       end  
0      2022-02-24 09:52:28  
1      2022-02-24 17:11:43  
2      2022-02-24 16:10:42  
3      2022-02-24 20:59:47  
4      2022-02-25 09:00:19  
...                    ...  
55783  2025-03-01 23:24:45  
55784  2025-03-02 01:38:57  
55785  2025-03-02 00:55:18  
55786  2025-03-02 02:44:07  
55787  2025-03-02 02:43:26  

[55788 rows x 6 columns]

### **2. Display the number of rows and columns in the DataFrame, the data types of the DataFrame columns, as well as the first few rows to ensure that the dataset has been loaded correctly.**


In [452]:
# Output the number of rows and columns in a DataFrame
df.shape

(55788, 6)

In [453]:
# Output DataFrame column types
df.dtypes

id              int64
region_id       int64
region_city    object
all_region      int64
start          object
end            object
dtype: object

In [454]:
# Outputting information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55788 entries, 0 to 55787
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   id           55788 non-null  int64 
 1   region_id    55788 non-null  int64 
 2   region_city  55788 non-null  object
 3   all_region   55788 non-null  int64 
 4   start        55788 non-null  object
 5   end          55788 non-null  object
dtypes: int64(3), object(3)
memory usage: 2.6+ MB


In [455]:
# Output the first few rows of the DataFrame
df.head()

id  region_id         region_city  all_region                start  \
0  52432         12      Львівська обл.           1  2022-02-24 07:43:17   
1  53292         23   Чернігівська обл.           1  2022-02-24 14:00:43   
2  52080          3      Вінницька обл.           1  2022-02-24 15:40:42   
3  52857         19     Харківська обл.           1  2022-02-24 20:11:47   
4  52700         18  Тернопільська обл.           1  2022-02-25 01:59:36   

                   end  
0  2022-02-24 09:52:28  
1  2022-02-24 17:11:43  
2  2022-02-24 16:10:42  
3  2022-02-24 20:59:47  
4  2022-02-25 09:00:19

In [456]:
len(df['region_city'].unique())

25

In [457]:
df['region_city'].unique()

array(['Львівська обл.', 'Чернігівська обл.', 'Вінницька обл.',
       'Харківська обл.', 'Тернопільська обл.', 'Київ', 'Рівненська обл.',
       'Черкаська обл.', 'Одеська обл.', 'Запорізька обл.',
       'Волинська обл.', 'Житомирська обл.', 'Херсонська обл.',
       'Миколаївська обл.', 'Хмельницька обл.', 'Івано-Франківська обл.',
       'Дніпропетровська обл.', 'Кіровоградська обл.', 'Чернівецька обл.',
       'Полтавська обл.', 'Київська обл.', 'Сумська обл.',
       'Донецька обл.', 'Закарпатська обл.', 'Крим'], dtype=object)

#**Find and remove duplicates**

In [458]:
duplicates = df[df.duplicated(subset=['region_city', 'start'], keep=False)]

if not duplicates.empty:
    print("Duplicates found:")
    print(duplicates)

    df = df.drop_duplicates(subset=['region_city', 'start'], keep='first')
    print("\nDuplicates removed.")
else:
    print("No duplicates found.")

duplicates_after = df[df.duplicated(subset=['region_city', 'start'], keep=False)]

if not duplicates_after.empty:
    print("Duplicates found after removal:")
    print(duplicates_after)
else:
    print("No duplicates found after deletion.")

Duplicates found:
          id  region_id      region_city  all_region                start  \
14156  68879         19  Харківська обл.           1  2022-12-18 12:07:13   
14157  68880         19  Харківська обл.           1  2022-12-18 12:07:13   

                       end  
14156  2022-12-18 12:37:13  
14157  2022-12-18 12:36:33  

Duplicates removed.
No duplicates found after deletion.


### **Splitting columns 'start', 'end' into separate values**

In [459]:
df['start'] = pd.to_datetime(df['start'])
df['end'] = pd.to_datetime(df['end'])

<ipython-input-459-1a9502253bfc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start'] = pd.to_datetime(df['start'])
<ipython-input-459-1a9502253bfc>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['end'] = pd.to_datetime(df['end'])


In [460]:
df['start_year'] = df['start'].dt.year
df['start_month'] = df['start'].dt.month
df['start_day'] = df['start'].dt.day
df['start_hour'] = df['start'].dt.hour
df['start_minute'] = df['start'].dt.minute
df['start_second'] = df['start'].dt.second

df['end_year'] = df['end'].dt.year
df['end_month'] = df['end'].dt.month
df['end_day'] = df['end'].dt.day
df['end_hour'] = df['end'].dt.hour
df['end_minute'] = df['end'].dt.minute
df['end_second'] = df['end'].dt.second

<ipython-input-460-356d72816367>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start_year'] = df['start'].dt.year
<ipython-input-460-356d72816367>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start_month'] = df['start'].dt.month
<ipython-input-460-356d72816367>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/

In [461]:
df.head()

id  region_id         region_city  all_region               start  \
0  52432         12      Львівська обл.           1 2022-02-24 07:43:17   
1  53292         23   Чернігівська обл.           1 2022-02-24 14:00:43   
2  52080          3      Вінницька обл.           1 2022-02-24 15:40:42   
3  52857         19     Харківська обл.           1 2022-02-24 20:11:47   
4  52700         18  Тернопільська обл.           1 2022-02-25 01:59:36   

                  end  start_year  start_month  start_day  start_hour  \
0 2022-02-24 09:52:28        2022            2         24           7   
1 2022-02-24 17:11:43        2022            2         24          14   
2 2022-02-24 16:10:42        2022            2         24          15   
3 2022-02-24 20:59:47        2022            2         24          20   
4 2022-02-25 09:00:19        2022            2         25           1   

   start_minute  start_second  end_year  end_month  end_day  end_hour  \
0            43            17      2022          2       24         9   
1             0            43      2022          2       24        17   
2            40            42      2022          2       24        16   
3            11            47      2022          2       24        20   
4            59            36      2022          2       25         9   

   end_minute  end_second  
0          52          28  
1          11          43  
2          10          42  
3          59          47  
4           0          19

### **Output statistics for each qualitative feature: the number of unique values ​​of the feature and the frequency of each unique value. Are there qualitative features with one unique value?**


In [462]:
# Dataframe with qualitative features
df_q = df['region_city']

In [463]:
# Number of unique feature values
df_q.nunique()

25

In [464]:
df_q.unique()

array(['Львівська обл.', 'Чернігівська обл.', 'Вінницька обл.',
       'Харківська обл.', 'Тернопільська обл.', 'Київ', 'Рівненська обл.',
       'Черкаська обл.', 'Одеська обл.', 'Запорізька обл.',
       'Волинська обл.', 'Житомирська обл.', 'Херсонська обл.',
       'Миколаївська обл.', 'Хмельницька обл.', 'Івано-Франківська обл.',
       'Дніпропетровська обл.', 'Кіровоградська обл.', 'Чернівецька обл.',
       'Полтавська обл.', 'Київська обл.', 'Сумська обл.',
       'Донецька обл.', 'Закарпатська обл.', 'Крим'], dtype=object)

In [465]:
# Counting the frequency of each unique value
index = 'region_city'

print(f"________________________________________________ \n Frequency of appearing for different values of '{index}': \n")
display(df['region_city'].value_counts())

________________________________________________ 
 Frequency of appearing for different values of 'region_city': 



region_city
Донецька обл.             5886
Харківська обл.           5651
Запорізька обл.           5494
Дніпропетровська обл.     4966
Полтавська обл.           3499
Сумська обл.              3251
Миколаївська обл.         3123
Херсонська обл.           3031
Кіровоградська обл.       2913
Черкаська обл.            2119
Чернігівська обл.         2074
Одеська обл.              1937
Київська обл.             1654
Київ                      1552
Вінницька обл.            1373
Житомирська обл.          1334
Хмельницька обл.           968
Рівненська обл.            833
Тернопільська обл.         771
Волинська обл.             757
Івано-Франківська обл.     676
Львівська обл.             672
Чернівецька обл.           665
Закарпатська обл.          581
Крим                         7
Name: count, dtype: int64

### **Output the same statistics for qualitative characteristics, but within each class.**


In [466]:
display(df.groupby(['region_city']).nunique())
display(df.groupby(['region_city']).value_counts())

id  region_id  all_region  start   end  start_year  \
region_city                                                                    
Івано-Франківська обл.   676          1           1    676   676           4   
Волинська обл.           757          1           1    757   757           4   
Вінницька обл.          1373          1           1   1373  1373           4   
Дніпропетровська обл.   4966          1           1   4966  4966           4   
Донецька обл.           5886          1           1   5886  5886           4   
Житомирська обл.        1334          1           1   1334  1334           4   
Закарпатська обл.        581          1           1    581   581           4   
Запорізька обл.         5494          1           1   5494  5494           4   
Київ                    1552          1           1   1552  1552           4   
Київська обл.           1654          1           1   1654  1654           4   
Крим                       7          1           1      7     7           1   
Кіровоградська обл.     2913          1           1   2913  2913           4   
Львівська обл.           672          1           1    672   672           4   
Миколаївська обл.       3123          1           1   3123  3123           4   
Одеська обл.            1937          1           1   1937  1937           4   
Полтавська обл.         3499          1           1   3499  3498           4   
Рівненська обл.          833          1           1    833   833           4   
Сумська обл.            3251          1           1   3251  3251           4   
Тернопільська обл.       771          1           1    771   771           4   
Харківська обл.         5651          1           1   5651  5651           4   
Херсонська обл.         3031          1           1   3031  3031           4   
Хмельницька обл.         968          1           1    968   968           4   
Черкаська обл.          2119          1           1   2119  2119           4   
Чернівецька обл.         665          1           1    665   665           4   
Чернігівська обл.       2074          1           1   2074  2074           4   

                        start_month  start_day  start_hour  start_minute  \
region_city                                                                
Івано-Франківська обл.           12         31          24            60   
Волинська обл.                   12         31          24            60   
Вінницька обл.                   12         31          24            60   
Дніпропетровська обл.            12         31          24            60   
Донецька обл.                    12         31          24            60   
Житомирська обл.                 12         31          24            60   
Закарпатська обл.                12         31          24            60   
Запорізька обл.                  12         31          24            60   
Київ                             12         31          24            60   
Київська обл.                    12         31          24            60   
Крим                              2          7           5             4   
Кіровоградська обл.              12         31          24            60   
Львівська обл.                   12         31          24            60   
Миколаївська обл.                12         31          24            60   
Одеська обл.                     12         31          24            60   
Полтавська обл.                  12         31          24            60   
Рівненська обл.                  12         31          24            60   
Сумська обл.                     12         31          24            60   
Тернопільська обл.               12         31          24            60   
Харківська обл.                  12         31          24            60   
Херсонська обл.                  12         31          24            60   
Хмельницька обл.                 12         31          24            60   
Черкаська обл.                   12      

region_city             id      region_id  all_region  start                end                  start_year  start_month  start_day  start_hour  start_minute  start_second  end_year  end_month  end_day  end_hour  end_minute  end_second
Івано-Франківська обл.  139     24         1           2022-03-01 15:42:44  2022-03-01 15:57:44  2022        3            1          15          42            44            2022      3          1        15        57          44            1
                        211     24         1           2022-03-02 20:30:12  2022-03-02 20:58:09  2022        3            2          20          30            12            2022      3          2        20        58          9             1
                        223     24         1           2022-03-02 21:03:04  2022-03-02 21:24:39  2022        3            2          21          3             4             2022      3          2        21        24          39            1
                        240     24         1           2022-03-03 01:51:54  2022-03-03 02:41:26  2022        3            3          1           51            54            2022      3          3        2         41          26            1
                        566     24         1           2022-03-06 22:06:13  2022-03-06 22:11:45  2022        3            6          22          6             13            2022      3          6        22        11          45            1
                                                                                                                                                                                                                                              ..
Чернігівська обл.       158496  23         1           2025-02-26 20:55:22  2025-02-27 04:33:36  2025        2            26         20          55            22            2025      2          27       4         33          36            1
                        158538  23         1           2025-02-27 20:54:06  2025-02-28 03:20:57  2025        2            27         20          54            6             2025      2          28       3         20          57            1
                        158603  23         1           2025-02-28 17:28:53  2025-02-28 18:02:23  2025        2            28         17          28            53            2025      2          28       18        2           23            1
                        158604  23         1           2025-02-28 21:50:35  2025-03-01 03:00:16  2025        2            28         21          50            35            2025      3          1        3         0           16            1
                        158665  23         1           2025-03-01 21:09:11  2025-03-02 00:59:20  2025        3            1          21          9             11            2025      3          2        0         59          20            1
Name: count, Length: 55787, dtype: int64

In [467]:
classific = df[['region_city']]

In [468]:
# Experiments to find dependencies between indicators
for index in classific:
    print(f"________________________________________________ \n Results of grouping by '{index}': \n")
    display(df.groupby([index]).nunique())
    display(df.groupby([index]).value_counts())

________________________________________________ 
 Results of grouping by 'region_city': 



id  region_id  all_region  start   end  start_year  \
region_city                                                                    
Івано-Франківська обл.   676          1           1    676   676           4   
Волинська обл.           757          1           1    757   757           4   
Вінницька обл.          1373          1           1   1373  1373           4   
Дніпропетровська обл.   4966          1           1   4966  4966           4   
Донецька обл.           5886          1           1   5886  5886           4   
Житомирська обл.        1334          1           1   1334  1334           4   
Закарпатська обл.        581          1           1    581   581           4   
Запорізька обл.         5494          1           1   5494  5494           4   
Київ                    1552          1           1   1552  1552           4   
Київська обл.           1654          1           1   1654  1654           4   
Крим                       7          1           1      7     7           1   
Кіровоградська обл.     2913          1           1   2913  2913           4   
Львівська обл.           672          1           1    672   672           4   
Миколаївська обл.       3123          1           1   3123  3123           4   
Одеська обл.            1937          1           1   1937  1937           4   
Полтавська обл.         3499          1           1   3499  3498           4   
Рівненська обл.          833          1           1    833   833           4   
Сумська обл.            3251          1           1   3251  3251           4   
Тернопільська обл.       771          1           1    771   771           4   
Харківська обл.         5651          1           1   5651  5651           4   
Херсонська обл.         3031          1           1   3031  3031           4   
Хмельницька обл.         968          1           1    968   968           4   
Черкаська обл.          2119          1           1   2119  2119           4   
Чернівецька обл.         665          1           1    665   665           4   
Чернігівська обл.       2074          1           1   2074  2074           4   

                        start_month  start_day  start_hour  start_minute  \
region_city                                                                
Івано-Франківська обл.           12         31          24            60   
Волинська обл.                   12         31          24            60   
Вінницька обл.                   12         31          24            60   
Дніпропетровська обл.            12         31          24            60   
Донецька обл.                    12         31          24            60   
Житомирська обл.                 12         31          24            60   
Закарпатська обл.                12         31          24            60   
Запорізька обл.                  12         31          24            60   
Київ                             12         31          24            60   
Київська обл.                    12         31          24            60   
Крим                              2          7           5             4   
Кіровоградська обл.              12         31          24            60   
Львівська обл.                   12         31          24            60   
Миколаївська обл.                12         31          24            60   
Одеська обл.                     12         31          24            60   
Полтавська обл.                  12         31          24            60   
Рівненська обл.                  12         31          24            60   
Сумська обл.                     12         31          24            60   
Тернопільська обл.               12         31          24            60   
Харківська обл.                  12         31          24            60   
Херсонська обл.                  12         31          24            60   
Хмельницька обл.                 12         31          24            60   
Черкаська обл.                   12      

region_city             id      region_id  all_region  start                end                  start_year  start_month  start_day  start_hour  start_minute  start_second  end_year  end_month  end_day  end_hour  end_minute  end_second
Івано-Франківська обл.  139     24         1           2022-03-01 15:42:44  2022-03-01 15:57:44  2022        3            1          15          42            44            2022      3          1        15        57          44            1
                        211     24         1           2022-03-02 20:30:12  2022-03-02 20:58:09  2022        3            2          20          30            12            2022      3          2        20        58          9             1
                        223     24         1           2022-03-02 21:03:04  2022-03-02 21:24:39  2022        3            2          21          3             4             2022      3          2        21        24          39            1
                        240     24         1           2022-03-03 01:51:54  2022-03-03 02:41:26  2022        3            3          1           51            54            2022      3          3        2         41          26            1
                        566     24         1           2022-03-06 22:06:13  2022-03-06 22:11:45  2022        3            6          22          6             13            2022      3          6        22        11          45            1
                                                                                                                                                                                                                                              ..
Чернігівська обл.       158496  23         1           2025-02-26 20:55:22  2025-02-27 04:33:36  2025        2            26         20          55            22            2025      2          27       4         33          36            1
                        158538  23         1           2025-02-27 20:54:06  2025-02-28 03:20:57  2025        2            27         20          54            6             2025      2          28       3         20          57            1
                        158603  23         1           2025-02-28 17:28:53  2025-02-28 18:02:23  2025        2            28         17          28            53            2025      2          28       18        2           23            1
                        158604  23         1           2025-02-28 21:50:35  2025-03-01 03:00:16  2025        2            28         21          50            35            2025      3          1        3         0           16            1
                        158665  23         1           2025-03-01 21:09:11  2025-03-02 00:59:20  2025        3            1          21          9             11            2025      3          2        0         59          20            1
Name: count, Length: 55787, dtype: int64

### **Check for gaps in the data set, display the number of missing values ​​in each column.**

In [469]:
for column in df.columns:
    display(df[column].unique())

array([ 52432,  53292,  52080, ..., 158636, 158617, 158629])

array([12, 23,  3, 19, 18,  9, 16, 22, 14,  8,  2,  6, 20, 13, 21, 24,  4,
       10,  1, 15, 17,  5,  7, 25])

array(['Львівська обл.', 'Чернігівська обл.', 'Вінницька обл.',
       'Харківська обл.', 'Тернопільська обл.', 'Київ', 'Рівненська обл.',
       'Черкаська обл.', 'Одеська обл.', 'Запорізька обл.',
       'Волинська обл.', 'Житомирська обл.', 'Херсонська обл.',
       'Миколаївська обл.', 'Хмельницька обл.', 'Івано-Франківська обл.',
       'Дніпропетровська обл.', 'Кіровоградська обл.', 'Чернівецька обл.',
       'Полтавська обл.', 'Київська обл.', 'Сумська обл.',
       'Донецька обл.', 'Закарпатська обл.', 'Крим'], dtype=object)

array([1, 0])

<DatetimeArray>
['2022-02-24 07:43:17', '2022-02-24 14:00:43', '2022-02-24 15:40:42',
 '2022-02-24 20:11:47', '2022-02-25 01:59:36', '2022-02-25 04:01:42',
 '2022-02-25 04:56:47', '2022-02-25 06:46:43', '2022-02-25 06:53:17',
 '2022-02-25 07:19:04',
 ...
 '2025-03-01 19:45:12', '2025-03-01 20:06:26', '2025-03-01 20:15:17',
 '2025-03-01 20:15:31', '2025-03-01 20:56:32', '2025-03-01 21:09:11',
 '2025-03-01 21:49:30', '2025-03-01 22:20:51', '2025-03-01 22:52:10',
 '2025-03-01 23:26:07']
Length: 54505, dtype: datetime64[ns]

<DatetimeArray>
['2022-02-24 09:52:28', '2022-02-24 17:11:43', '2022-02-24 16:10:42',
 '2022-02-24 20:59:47', '2022-02-25 09:00:19', '2022-02-25 08:35:42',
 '2022-02-25 05:40:47', '2022-02-25 06:52:43', '2022-02-25 07:56:28',
 '2022-02-25 07:49:04',
 ...
 '2025-03-02 01:40:15', '2025-03-01 23:44:05', '2025-03-02 00:55:15',
 '2025-03-02 01:37:46', '2025-03-02 00:59:20', '2025-03-01 23:24:45',
 '2025-03-02 01:38:57', '2025-03-02 00:55:18', '2025-03-02 02:44:07',
 '2025-03-02 02:43:26']
Length: 54376, dtype: datetime64[ns]

array([2022, 2023, 2024, 2025], dtype=int32)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1], dtype=int32)

array([24, 25, 26, 27, 28,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 29, 30, 31],
      dtype=int32)

array([ 7, 14, 15, 20,  1,  4,  6, 11, 12, 13, 16, 17, 18, 19, 21, 22,  5,
        8,  9, 10, 23,  0,  2,  3], dtype=int32)

array([43,  0, 40, 11, 59,  1, 56, 46, 53, 19, 41, 50, 17, 54,  8,  5, 38,
       13, 24,  3, 55, 18, 36, 26, 16, 35, 39, 20, 58, 44, 12, 10, 14, 45,
       48,  4, 25, 28,  6,  9, 34, 37, 57,  7, 51, 52, 21, 15, 32, 47, 31,
       22, 23,  2, 49, 27, 29, 33, 30, 42], dtype=int32)

array([17, 43, 42, 47, 36,  4, 53,  7, 58,  6, 26, 39, 54, 23, 41, 44, 29,
       20, 22, 55,  3, 57,  1, 14, 18, 10, 19, 46, 31, 33, 21, 38,  0, 35,
       34, 37, 40, 11,  5, 28, 51,  2,  9, 25, 50, 32, 13, 59,  8, 45, 16,
       27, 12, 48, 49, 52, 24, 30, 56, 15], dtype=int32)

array([2022, 2023, 2024, 2025], dtype=int32)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1], dtype=int32)

array([24, 25, 26, 27, 28,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 29, 30, 31],
      dtype=int32)

array([ 9, 17, 16, 20,  8,  5,  6,  7, 11, 12, 13, 14, 21, 23, 10, 15, 18,
       19, 22,  1,  2,  0,  3,  4], dtype=int32)

array([52, 11, 10, 59,  0, 35, 40, 56, 49, 50, 21, 26, 58, 31,  4, 24, 30,
       36, 45, 41, 54, 33, 13, 15, 34, 47,  5, 42, 48, 20,  6, 27, 39, 43,
       19, 57, 22, 16, 44, 28,  3, 18, 12,  7, 23,  2, 38, 37, 51, 14, 32,
       53, 55, 17,  8,  1, 46,  9, 25, 29], dtype=int32)

array([28, 43, 42, 47, 19,  4, 46, 58,  6, 26, 53, 39,  7,  3, 36, 41, 40,
       25, 57, 37, 44, 50, 49, 15, 31,  9, 29, 20, 12, 38,  5, 14, 34, 24,
       33, 30, 56, 32, 45,  1, 54,  0, 11, 23, 48, 51, 13,  2, 18, 16, 21,
       10, 55, 59, 22,  8, 52, 27, 17, 35], dtype=int32)

In [470]:
df = df.replace(' ?', np.nan)

In [471]:
df.isnull().sum()

id              0
region_id       0
region_city     0
all_region      0
start           0
end             0
start_year      0
start_month     0
start_day       0
start_hour      0
start_minute    0
start_second    0
end_year        0
end_month       0
end_day         0
end_hour        0
end_minute      0
end_second      0
dtype: int64

In [472]:
for column in df.columns:
    null_count = df[column].isnull().sum()
    print(null_count/len(df))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


### **Looking for incorrect values**

In [473]:
invalid_entries = df[df['end'] < df['start']]

count_invalid = invalid_entries.shape[0]
print(f"The number of incorrect values: {count_invalid}")

The number of incorrect values: 1


In [474]:
df = df[df['end'] >= df['start']]

In [475]:
invalid_entries = df[df['end'] < df['start']]

count_invalid = invalid_entries.shape[0]
print(f"The number of incorrect values: {count_invalid}")

The number of incorrect values: 0


##**Creating new columns to better train the model**

In [476]:
df['duration_hours'] = (df['end'] - df['start']).dt.total_seconds() / 3600

df['day_of_week'] = df['start'].dt.day_name()

df['is_weekend'] = df['start'].dt.dayofweek >= 5
df['is_weekend'] = df['is_weekend'].astype(int)

<ipython-input-476-565f1ddf59dc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['duration_hours'] = (df['end'] - df['start']).dt.total_seconds() / 3600
<ipython-input-476-565f1ddf59dc>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day_of_week'] = df['start'].dt.day_name()
<ipython-input-476-565f1ddf59dc>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http

In [477]:
events = pd.concat([
    df[['start']].rename(columns={'start': 'time'}).assign(change=1),
    df[['end']].rename(columns={'end': 'time'}).assign(change=-1)
])

events = events.sort_values('time')
events['active_regions_count'] = events['change'].cumsum()

df = pd.merge_asof(
    df.sort_values('start'),
    events[['time', 'active_regions_count']].sort_values('time'),
    left_on='start',
    right_on='time'
)
df = df.drop(columns='time')

In [478]:
df.head()

id  region_id         region_city  all_region               start  \
0  52432         12      Львівська обл.           1 2022-02-24 07:43:17   
1  53292         23   Чернігівська обл.           1 2022-02-24 14:00:43   
2  52080          3      Вінницька обл.           1 2022-02-24 15:40:42   
3  52857         19     Харківська обл.           1 2022-02-24 20:11:47   
4  52700         18  Тернопільська обл.           1 2022-02-25 01:59:36   

                  end  start_year  start_month  start_day  start_hour  ...  \
0 2022-02-24 09:52:28        2022            2         24           7  ...   
1 2022-02-24 17:11:43        2022            2         24          14  ...   
2 2022-02-24 16:10:42        2022            2         24          15  ...   
3 2022-02-24 20:59:47        2022            2         24          20  ...   
4 2022-02-25 09:00:19        2022            2         25           1  ...   

   end_year  end_month  end_day  end_hour  end_minute  end_second  \
0      2022          2       24         9          52          28   
1      2022          2       24        17          11          43   
2      2022          2       24        16          10          42   
3      2022          2       24        20          59          47   
4      2022          2       25         9           0          19   

   duration_hours  day_of_week  is_weekend active_regions_count  
0        2.153056     Thursday           0                    1  
1        3.183333     Thursday           0                    1  
2        0.500000     Thursday           0                    2  
3        0.800000     Thursday           0                    1  
4        7.011944       Friday           0                    1  

[5 rows x 22 columns]

### **Removing the 'start', 'end' columns, as we no longer need them after dividing them into separate columns**

In [479]:
df = df.drop(columns=['start', 'end'])

### **Allocation of areas to each separate column**

In [480]:
dummies = pd.get_dummies(df['region_city'], drop_first=True)
dummies = dummies.astype(int)
df = df.drop(columns=['region_city']).join(dummies)
df

id  region_id  all_region  start_year  start_month  start_day  \
0       52432         12           1        2022            2         24   
1       53292         23           1        2022            2         24   
2       52080          3           1        2022            2         24   
3       52857         19           1        2022            2         24   
4       52700         18           1        2022            2         25   
...       ...        ...         ...         ...          ...        ...   
55781  158642         14           1        2025            3          1   
55782  158635          9           1        2025            3          1   
55783  158636          9           0        2025            3          1   
55784  158617          3           1        2025            3          1   
55785  158629          6           1        2025            3          1   

       start_hour  start_minute  start_second  end_year  ...  Полтавська обл.  \
0               7            43            17      2022  ...                0   
1              14             0            43      2022  ...                0   
2              15            40            42      2022  ...                0   
3              20            11            47      2022  ...                0   
4               1            59            36      2022  ...                0   
...           ...           ...           ...       ...  ...              ...   
55781          21            49            30      2025  ...                0   
55782          22            20            51      2025  ...                0   
55783          22            52            10      2025  ...                0   
55784          23            26             7      2025  ...                0   
55785          23            26             7      2025  ...                0   

       Рівненська обл.  Сумська обл.  Тернопільська обл.  Харківська обл.  \
0                    0             0                   0                0   
1                    0             0                   0                0   
2                    0             0                   0                0   
3                    0             0                   0                1   
4                    0             0                   1                0   
...                ...           ...                 ...              ...   
55781                0             0                   0                0   
55782                0             0                   0                0   
55783                0             0                   0                0   
55784                0             0                   0                0   
55785                0             0                   0                0   

       Херсонська обл. Хмельницька обл.  Черкаська обл.  Чернівецька обл.  \
0                    0                0               0                 0   
1                    0                0               0                 0   
2                    0                0               0                 0   
3                    0                0               0                 0   
4                    0                0               0                 0   
...                ...              ...             ...               ...   
55781                0                0               0                 0   
55782                0                0               0                 0   
55783                0                0               0                 0   
55784                0                0               0                 0   
55785                0                0               0                 0   

       Чернігівська обл.  
0                      0  
1                      1  
2                      0  
3                      0  
4                      0  
...                  ...  
55781                  0  
55782                  0  
55783                  0  
55784

In [481]:
df = df.drop('region_id', axis=1)

In [482]:
df.head()

id  all_region  start_year  start_month  start_day  start_hour  \
0  52432           1        2022            2         24           7   
1  53292           1        2022            2         24          14   
2  52080           1        2022            2         24          15   
3  52857           1        2022            2         24          20   
4  52700           1        2022            2         25           1   

   start_minute  start_second  end_year  end_month  ...  Полтавська обл.  \
0            43            17      2022          2  ...                0   
1             0            43      2022          2  ...                0   
2            40            42      2022          2  ...                0   
3            11            47      2022          2  ...                0   
4            59            36      2022          2  ...                0   

   Рівненська обл.  Сумська обл.  Тернопільська обл.  Харківська обл.  \
0                0             0                   0                0   
1                0             0                   0                0   
2                0             0                   0                0   
3                0             0                   0                1   
4                0             0                   1                0   

  Херсонська обл.  Хмельницька обл.  Черкаська обл.  Чернівецька обл.  \
0               0                 0               0                 0   
1               0                 0               0                 0   
2               0                 0               0                 0   
3               0                 0               0                 0   
4               0                 0               0                 0   

   Чернігівська обл.  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0  

[5 rows x 42 columns]

### **Saving a new dataset**

In [483]:
df.to_csv('alarms_new_.csv', index=False)